server:
  name: etcd_test
  author: airing
  version: 1.0
  port: 8080
  netTimeOutMs: 0

log:
  level: debug
  path: ../log/
  maxSize: 100   #mb
  maxBackups: 20 #file count
  maxAge: 30     #days
  compress: true

etcd:
  addrs: ["127.0.0.1:2380"]

udp_client:
  serverName: netserver_test
  addr: etcd:netserver_test
  timeOutMs: 5000